In [19]:
import numpy as np

class LeakyReLU:
    def __init__(self, alpha=0.01):
        self.alpha = alpha
        self.mask = None

    def forward(self, input_tensor):
        self.mask = (input_tensor <= 0)
        return np.where(
            input_tensor > 0, 
            input_tensor, 
            input_tensor * self.alpha
        )

    def backward(self, error_tensor):
        return np.where(
            error_tensor > 0, 
            1, 
            self.alpha
        )

In [20]:
x = np.array([[1.0, -4], [-15, 3.0]])
print(x)

[[  1.  -4.]
 [-15.   3.]]


In [21]:
lr = LeakyReLU()

In [22]:
print(lr.forward(x))

[[ 1.   -0.04]
 [-0.15  3.  ]]


In [18]:
print(lr.backward(x))

[[1.   0.01]
 [0.01 1.  ]]
