In [8]:
import numpy as np

class Relu:
    def __init__(self):
        self.mask = None

    def forward(self, input_tensor):
        self.mask = (input_tensor <= 0)
        out = input_tensor.copy()
        out[self.mask] = 0

        return out

    def backward(self, error_tensor):
        error_tensor[self.mask] = 0
        dx = error_tensor

        return dx

In [9]:
x = np.array([[1.0, -0.5], [-2.0, 3.0]])

In [10]:
relu = Relu()

In [11]:
relu.forward(x)

array([[1., 0.],
       [0., 3.]])

In [12]:
relu.mask

array([[False,  True],
       [ True, False]])

In [13]:
relu.backward(x)

array([[1., 0.],
       [0., 3.]])